# Required
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'leico/autodate.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
  let g:coc_global_extensions = ['coc-json', 'coc-css', 'coc-eslint', 'coc-prettier', 'coc-tsserver', 'coc-toml', 'coc-yaml']
  
  nmap <silent> [g <Plug>(coc-diagnostic-prev)
  nmap <silent> ]g <Plug>(coc-diagnostic-next)

  " GoTo code navigation.
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window
  nnoremap <silent> K :call <SID>show_documentation()<CR>

  function! s:show_documentation()
    if (index(['vim','help'], &filetype) >= 0)
      execute 'h '.expand('<cword>')
    else
      call CocAction('doHover')
    endif
  endfunction" 
'''

# System plugins
# [[plugins]]
#  repo = 'preservim/nerdtree'
#  hook_add = '''
#    let NERDTreeShowHidden = 1
#    map <C-n> :NERDTreeToggle<CR>
#  '''
# [[plugins]]
# repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  let g:fern#renderer = "nerdfont"
  let g:fern#disable_drawer_smart_quit = 1
  nmap <silent><C-e> :Fern . -drawer -toggle<CR>
'''
[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = '''
  nnoremap <silent><C-t> :<C-u>Deol -split=floating<CR>
  tnoremap <ESC>   <C-\><C-n>
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme = 'codedark'
'''

[[plugins]]
repo = 'puremourning/vimspector'
on_ft = ["javascript","typescript","typescriptreact"]
build = "./install_gadget.py --enable-python --force-enable-chrome --force-enable-node"
hook_add = '''
  let g:vimspector_enable_mappings='HUMAN'
'''

# Theme and colorscheme
[[plugins]]
repo = 'tomasiser/vim-code-dark'
hook_add = '''
  autocmd! VimEnter * nested colorscheme codedark
'''

[[plugins]]
repo = 'inkarkat/vim-SyntaxRange'

[[plugins]]
repo = 'thaerkh/vim-workspace'

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'kdheepak/lazygit.nvim'
hook_add = '''
  nnoremap <silent> <leader>lg :LazyGit<CR>
'''
# Common plugins
[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
"indentline"
let g:indentLine_color_term =239
let g:indentLine_color_gui = '#708090'
let g:indentLine_char = '¦'
let g:indentLine_char_list = ['|', '¦', '┆', '┊']

'''
# Language specific plugins
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

