# Required
[[plugins]]
repo = 'Shougo/dein.vim'

# coc.nvim
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = 'runtime! ./pluginconfigs/coc.rc.vim'

[[plugins]]
repo = 'voldikss/vim-floaterm'

# Debugger
[[plugins]]
repo = 'puremourning/vimspector'
on_ft = ["javascript","typescript","typescriptreact"]
build = "./install_gadget.py --enable-python --force-enable-chrome --force-enable-node"

# Denite
[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'neoclide/coc-denite'
hook_add = 'runtime! ./pluginconfigs/denite.rc.vim'

# Look and feel
[[plugins]]
repo = 'tomasiser/vim-code-dark'

[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = 'runtime! ./pluginconfigs/airline-themes.rc.vim'

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'kdheepak/lazygit.nvim'
hook_add = '''
  nnoremap <silent> <leader>lg :LazyGit<CR>
'''
[[plugins]]
repo = 'rbong/vim-flog'

# Common plugins
[[plugins]]
repo = 'jiangmiao/auto-pairs'
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'runtime! ./pluginconfigs/indentLine.rc.vim'

# Language specific plugins
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
