# Required
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'leico/autodate.vim'

# coc.nvim
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = 'runtime! ./pluginconfigs/coc.vim'
[[plugins]]
repo = 'liuchengxu/vim-clap'
[[plugins]]
repo = 'vn-ki/coc-clap'

# [[plugins]]
# repo = 'lambdalisue/fern.vim'
# hook_add = 'runtime! ./pluginconfigs/fern.vim'
# [[plugins]]
# repo = 'antoinemadec/FixCursorHold.nvim'
# [[plugins]]
# repo = 'lambdalisue/fern-git-status.vim'
# [[plugins]]
# repo = 'lambdalisue/fern-renderer-nerdfont.vim'
# [[plugins]]
# repo = 'lambdalisue/nerdfont.vim'
# [[plugins]]
# repo = 'lambdalisue/glyph-palette.vim'
# hook_add = 'runtime! ./pluginconfigs/glyph-palette.vim'

# [[plugins]]
# repo = 'Shougo/deol.nvim'
[[plugins]]
repo = 'voldikss/vim-floaterm'

[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = 'runtime! ./pluginconfigs/airline-themes.vim'

[[plugins]]
repo = 'puremourning/vimspector'
on_ft = ["javascript","typescript","typescriptreact"]
build = "./install_gadget.py --enable-python --force-enable-chrome --force-enable-node"

# Theme and colorscheme
[[plugins]]
repo = 'tomasiser/vim-code-dark'
[[plugins]]
repo = 'thaerkh/vim-workspace'

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'kdheepak/lazygit.nvim'
hook_add = '''
  nnoremap <silent> <leader>lg :LazyGit<CR>
'''
# Common plugins
[[plugins]]
repo = 'jiangmiao/auto-pairs'
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'runtime! ./pluginconfigs/indentLine.vim'

# Language specific plugins
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
# [[plugins]]
# repo = 'HerringtonDarkholme/yats.vim'
