return {
  nut = {
    buf = {
      diagnostic_count = require("nougat.nut.buf.diagnostic_count").create,
      filename = require("user.plugins.appearance.nougat.nut.buf.filename").create,
      filestatus = require("nougat.nut.buf.filestatus").create,
      filetype = require("user.plugins.appearance.nougat.nut.buf.filetype").create,
      icon = require("user.plugins.appearance.nougat.nut.buf.icon").create,
      navic = require("user.plugins.appearance.nougat.nut.buf.navic").create,
      fileformat = require("user.plugins.appearance.nougat.nut.buf.fileformat").create,
      encoding = require("user.plugins.appearance.nougat.nut.buf.encoding").create,
      fmo = require("user.plugins.appearance.nougat.nut.buf.fmo").create,
      copilot = require("user.plugins.appearance.nougat.nut.buf.copilot").create,
    },
    git = {
      branch = require("user.plugins.appearance.nougat.nut.git.branch").create,
      status = require("user.plugins.appearance.nougat.nut.git.status").create,
    },
    tab = {
      tablist = {
        tabs = require("nougat.nut.tab.tablist").create,
        close = require("nougat.nut.tab.tablist.close").create,
        icon = require("nougat.nut.tab.tablist.icon").create,
        label = require("nougat.nut.tab.tablist.label").create,
        modified = require("nougat.nut.tab.tablist.modified").create,
      },
    },
    lsp = {
      servers = require("nougat.nut.lsp.servers").create,
    },
    mode = require("user.plugins.appearance.nougat.nut.mode").create,
    spacer = require("nougat.nut.spacer").create,
    truncation_point = require("nougat.nut.truncation_point").create,
  },
  ---@type nougat.color
  color = require("nougat.color").get(),
  separators = {
    vertical_bar = "┃",
    vertical_bar_thin = "│",
    left = "",
    right = "",
    block = "█",
    left_filled = "",
    right_filled = "",
    slant_left = "",
    slant_left_thin = "",
    slant_right = "",
    slant_right_thin = "",
    slant_left_2 = "",
    slant_left_2_thin = "",
    slant_right_2 = "",
    slant_right_2_thin = "",
    left_rounded = "",
    left_rounded_thin = "",
    right_rounded = "",
    right_rounded_thin = "",
    circle = " ",
  },
}
