name: benchmark
on:
  workflow_dispatch:
  push:
    paths:
      - '**.lua'
      - '**.vim'
    branches:
      - master

jobs: 
  benchmark: 
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: nightly

    - name: Setup deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: copy config (Linux)
      if: runner.os == 'Linux'
      run: cp -r ./ ~/.config/nvim/

    - name: copy config (Windows)
      if: runner.os == 'Windows'
      run: cp -r ./ ~/AppData/Local/nvim/

    - name: Install plugins
      run: |
        nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
        nvim -c qa

    - name: Run benchmark
      run: |
        deno run --unstable --allow-all ./scripts/benchmark.ts

    - name: Upload benchmark
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: customSmallerIsBetter
        output-file-path: data.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        benchmark-data-dir-path: bench/${{ matrix.os }}
        auto-push: true
        comment-on-alert: true
        fail-on-alert: true
        alert-threshold: '150%'
        alert-comment-cc-users: '@nazo6'
