name: ci
on: [push]

jobs: 
  benchmark: 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ~/.config
    steps:
    - name: Setup neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: nightly

    - name: Setup deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Checkout config
      uses: actions/checkout@v2

    - name: Install plugins
      run: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

    - name: Run benchmark
      run: |
       cd ~/.config/nvim/
       deno run --unstable --allow-all scripts/benchmark.ts

    - name: Upload benchmark
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: customSmallerIsBetter
        output-file-path: data.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        comment-on-alert: true
        fail-on-alert: true
        alert-threshold: '150%'
        alert-comment-cc-users: '@nazo6'
